CREATE TABLE `customs_declarations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`declarationNumber` varchar(50) NOT NULL,
	`registrationDate` date NOT NULL,
	`clearanceCenter` varchar(100) NOT NULL,
	`exchangeRate` decimal(10,6) NOT NULL,
	`exportCountry` varchar(100) NOT NULL,
	`billOfLadingNumber` varchar(50) NOT NULL,
	`grossWeight` decimal(12,3) NOT NULL,
	`netWeight` decimal(12,3) NOT NULL,
	`numberOfPackages` int NOT NULL,
	`packageType` varchar(50) NOT NULL,
	`fobValue` decimal(15,3) NOT NULL,
	`fobValueJod` decimal(15,3) NOT NULL,
	`freightCost` decimal(12,3) NOT NULL,
	`insuranceCost` decimal(12,3) NOT NULL,
	`customsDuty` decimal(12,3) NOT NULL,
	`salesTax` decimal(12,3) NOT NULL,
	`additionalFees` decimal(12,3) DEFAULT '0',
	`customsServiceFee` decimal(12,3) DEFAULT '0',
	`penalties` decimal(12,3) DEFAULT '0',
	`estimatedFobValue` decimal(15,3) DEFAULT '0',
	`estimatedFreight` decimal(12,3) DEFAULT '0',
	`estimatedInsurance` decimal(12,3) DEFAULT '0',
	`estimatedCustomsDuty` decimal(12,3) DEFAULT '0',
	`estimatedSalesTax` decimal(12,3) DEFAULT '0',
	`estimatedAdditionalFees` decimal(12,3) DEFAULT '0',
	`totalLandedCost` decimal(15,3) NOT NULL,
	`additionalExpensesRatio` decimal(5,2) NOT NULL,
	`status` enum('draft','submitted','approved','cleared') DEFAULT 'draft',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `customs_declarations_id` PRIMARY KEY(`id`),
	CONSTRAINT `customs_declarations_declarationNumber_unique` UNIQUE(`declarationNumber`)
);
--> statement-breakpoint
CREATE TABLE `financial_summaries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`declarationId` int NOT NULL,
	`totalFobValue` decimal(15,3) NOT NULL,
	`totalFreightAndInsurance` decimal(12,3) NOT NULL,
	`totalCustomsAndTaxes` decimal(12,3) NOT NULL,
	`totalLandedCost` decimal(15,3) NOT NULL,
	`additionalExpensesRatio` decimal(5,2) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `financial_summaries_id` PRIMARY KEY(`id`),
	CONSTRAINT `financial_summaries_declarationId_unique` UNIQUE(`declarationId`)
);
--> statement-breakpoint
CREATE TABLE `items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`declarationId` int NOT NULL,
	`itemName` varchar(255) NOT NULL,
	`quantity` decimal(12,3) NOT NULL,
	`unitPriceForeign` decimal(12,3) NOT NULL,
	`totalPriceForeign` decimal(15,3) NOT NULL,
	`totalPriceJod` decimal(15,3) NOT NULL,
	`valuePercentage` decimal(5,2) NOT NULL,
	`itemExpensesShare` decimal(15,3) NOT NULL,
	`totalItemCostJod` decimal(15,3) NOT NULL,
	`unitCostJod` decimal(12,3) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `variances` (
	`id` int AUTO_INCREMENT NOT NULL,
	`declarationId` int NOT NULL,
	`fobVariance` decimal(15,3) NOT NULL,
	`freightVariance` decimal(12,3) NOT NULL,
	`insuranceVariance` decimal(12,3) NOT NULL,
	`customsDutyVariance` decimal(12,3) NOT NULL,
	`salesTaxVariance` decimal(12,3) NOT NULL,
	`totalVariance` decimal(15,3) NOT NULL,
	`fobVariancePercent` decimal(6,2) NOT NULL,
	`freightVariancePercent` decimal(6,2) NOT NULL,
	`insuranceVariancePercent` decimal(6,2) NOT NULL,
	`customsDutyVariancePercent` decimal(6,2) NOT NULL,
	`salesTaxVariancePercent` decimal(6,2) NOT NULL,
	`totalVariancePercent` decimal(6,2) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `variances_id` PRIMARY KEY(`id`),
	CONSTRAINT `variances_declarationId_unique` UNIQUE(`declarationId`)
);
