CREATE TABLE `factories` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`factoryName` varchar(255) NOT NULL,
	`factoryCode` varchar(50) NOT NULL,
	`country` varchar(100) NOT NULL,
	`contactPerson` varchar(255),
	`email` varchar(320),
	`phone` varchar(20),
	`address` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `factories_id` PRIMARY KEY(`id`),
	CONSTRAINT `factories_factoryCode_unique` UNIQUE(`factoryCode`)
);
--> statement-breakpoint
CREATE TABLE `invoice_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`invoiceId` int NOT NULL,
	`itemId` int NOT NULL,
	`productName` varchar(255) NOT NULL,
	`quantity` decimal(12,3) NOT NULL,
	`unitPrice` decimal(12,3) NOT NULL,
	`totalPrice` decimal(15,3) NOT NULL,
	`customsCode` varchar(50),
	`harmonizedCode` varchar(50),
	`tarifBand` varchar(50),
	`dutyRate` decimal(5,2) NOT NULL DEFAULT '0',
	`salesTaxRate` decimal(5,2) NOT NULL DEFAULT '16',
	`customsDuty` decimal(12,3) NOT NULL DEFAULT '0',
	`salesTax` decimal(12,3) NOT NULL DEFAULT '0',
	`allocatedExternalCosts` decimal(12,3) NOT NULL DEFAULT '0',
	`allocatedInternalCosts` decimal(12,3) NOT NULL DEFAULT '0',
	`finalUnitPrice` decimal(12,3) NOT NULL,
	`finalTotalPrice` decimal(15,3) NOT NULL,
	`description` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `invoice_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `invoices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`declarationId` int NOT NULL,
	`factoryId` int NOT NULL,
	`userId` int NOT NULL,
	`invoiceNumber` varchar(50) NOT NULL,
	`invoiceDate` date NOT NULL,
	`freightCost` decimal(12,3) NOT NULL DEFAULT '0',
	`insuranceCost` decimal(12,3) NOT NULL DEFAULT '0',
	`otherExternalCosts` decimal(12,3) NOT NULL DEFAULT '0',
	`localHandlingCosts` decimal(12,3) NOT NULL DEFAULT '0',
	`storageAndWarehouseCosts` decimal(12,3) NOT NULL DEFAULT '0',
	`customsClearanceCosts` decimal(12,3) NOT NULL DEFAULT '0',
	`otherInternalCosts` decimal(12,3) NOT NULL DEFAULT '0',
	`totalExternalCosts` decimal(12,3) NOT NULL,
	`totalInternalCosts` decimal(12,3) NOT NULL,
	`totalCosts` decimal(15,3) NOT NULL,
	`notes` text,
	`status` enum('draft','confirmed','completed') NOT NULL DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `invoices_id` PRIMARY KEY(`id`)
);
