DROP TABLE `analytics_dashboard`;--> statement-breakpoint
DROP TABLE `analytics_events`;--> statement-breakpoint
DROP TABLE `analytics_metrics`;--> statement-breakpoint
DROP TABLE `bank_accounts`;--> statement-breakpoint
DROP TABLE `bank_notifications`;--> statement-breakpoint
DROP TABLE `bank_transactions`;--> statement-breakpoint
DROP TABLE `bank_verifications`;--> statement-breakpoint
DROP TABLE `containers`;--> statement-breakpoint
DROP TABLE `customs_declarations`;--> statement-breakpoint
DROP TABLE `expense_types`;--> statement-breakpoint
DROP TABLE `expenses`;--> statement-breakpoint
DROP TABLE `factories`;--> statement-breakpoint
DROP TABLE `financial_summaries`;--> statement-breakpoint
DROP TABLE `invoice_items`;--> statement-breakpoint
DROP TABLE `invoices`;--> statement-breakpoint
DROP TABLE `items`;--> statement-breakpoint
DROP TABLE `notification_log`;--> statement-breakpoint
DROP TABLE `notification_preferences`;--> statement-breakpoint
DROP TABLE `notifications`;--> statement-breakpoint
DROP TABLE `payments`;--> statement-breakpoint
DROP TABLE `refunds`;--> statement-breakpoint
DROP TABLE `saved_calculations`;--> statement-breakpoint
DROP TABLE `saved_reports`;--> statement-breakpoint
DROP TABLE `shipment_details`;--> statement-breakpoint
DROP TABLE `stripe_invoices`;--> statement-breakpoint
DROP TABLE `subscription_invoices`;--> statement-breakpoint
DROP TABLE `subscriptions`;--> statement-breakpoint
DROP TABLE `tracking_events`;--> statement-breakpoint
DROP TABLE `user_alerts`;--> statement-breakpoint
DROP TABLE `user_preferences`;--> statement-breakpoint
DROP TABLE `variances`;--> statement-breakpoint
DROP TABLE `audit_log`;--> statement-breakpoint
DROP TABLE `chart_of_accounts`;--> statement-breakpoint
DROP TABLE `financial_reports`;--> statement-breakpoint
DROP TABLE `general_ledger`;--> statement-breakpoint
DROP TABLE `transactions`;--> statement-breakpoint
DROP TABLE `trial_balance`;--> statement-breakpoint
ALTER TABLE `users` DROP COLUMN `stripe_customer_id`;